steps:

  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','./desafio3/src/soma']
    env: ['GOPATH=.']

  - id: go_build
    name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', './desafio3/src/soma', './desafio3/src/soma]
    env: ['GOPATH=.']

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/desafio3:latest', './desafio3/']

  - id: docker_run 
    name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/desafio3']


# here the cloud build do the push automatically
images:
  - 'gcr.io/$PROJECT_ID/desafio3:latest'