steps:

  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','./desafio4/desafio-golang']
    env: ['GOPATH=.','CGO_ENABLED=0', 'GOOS=linux', 'GOARCH=amd64']

  - id: go_build
    name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', './desafio4/desafio-golang', './desafio4/desafio-golang']
    env: ['GOPATH=.']

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/challenge04-03:latest', './desafio4/desafio-golang/']


# here the cloud build do the push automatically
images:
  - 'gcr.io/$PROJECT_ID/challenge04-03:latest'