apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-golang
  labels:
    app: challenge-golang
spec:
  selector:
    matchLabels:
      app: challenge-golang
  replicas: 1
  template:
    metadata: 
      labels:
        app: challenge-golang
    spec:
      containers:

      - name: challenge-golang
        image: viniciosbinsfeld/code-education-go-webserver
        ports:
        - containerPort: 8000