apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-nginx
  labels:
    app: desafio-nginx
spec:
  selector:
    matchLabels:
      app: desafio-nginx
  replicas: 3
  template:  # pods
    metadata: 
      labels:
        app: desafio-nginx
    spec:
      containers:
      - name: desafio-nginx
        image: nginx:1.17-alpine
        resources:
          limits:
            memory: "128Mi"
          requests:
            memory: 32Mi  
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /etc/nginx/conf.d  # Config que ira sobrescrever o nginx.conf
          name: nginx-conf              # namo do volume
          readOnly: true

      volumes:                # especificação do volume
      - name: nginx-conf
        configMap:            # our configmap with the nginx definition
          name: nginx-conf-desafio
          items:
          - key: nginx.conf
            path: nginx.conf  # file name with key: nginx.conf content
        